site_name: Гайд по Aiogram
site_url: https://a6dall.github.io/aiogram-guide/

theme:
  name: material
  language: ru
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share
  palette:
    - scheme: slate  # ← тёмная тема по умолчанию
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
    - scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Тёмная тема
  font:
    text: Roboto
    code: Fira Code

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.keys

nav:
  - Главная: index.md
  - Установка: install.md
  - Хэндлеры: handlers.md
  - FSM:
      - Основы: fsm/index.md
      - Состояния: fsm/states.md
