site_name: Гайд по Aiogram
site_url: https://a6dall.github.io/aiogram-guide/
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Переключить тему
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.sections         # ← ✅ включает навигацию слева
    - navigation.top             # ← кнопка наверх
    - content.code.copy          # ← кнопка копировать
    - search.highlight
    - search.share


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.keys

nav:
  - Главная: index.md
  - Установка: install.md
  - Хэндлеры: handlers.md
  - FSM:
      - Основы: fsm/index.md
      - Состояния: fsm/states.md

