site_name: ''  # Убираем лишний заголовок
site_url: https://a6dall.github.io/aiogram-guide/

theme:
  name: material
  language: ru
  logo: null
  include_homepage_in_sidebar: true
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
    - scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Тёмная тема
  font:
    text: Roboto
    code: Fira Code
  custom_dir: overrides

extra_css:
  - styles/extra.css  # ← наш CSS для правки меню

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.keys

nav:
  - Главная: index.md
  - Установка: install.md
  - Хэндлеры: handlers.md
  - FSM - Основы: fsm/index.md
  - FSM - Состояния: fsm/states.md
